server {
    listen 10000;
    server_name _;

    root /var/www/public;
    index index.php index.html;

    # CORS
    add_header 'Access-Control-Allow-Origin' 'https://tttn-2.onrender.com' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    # Handle preflight
    if ($request_method = OPTIONS) {
        return 204;
    }

    # MIME types (tránh browser chặn CSS)
    include /etc/nginx/mime.types;

    # Serve static files (Swagger UI dùng CSS/JS trong /vendor)
    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|map)$ {
        try_files $uri =404;
        expires 30d;
        access_log off;
    }

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ^~ /vendor/ {
    root /var/www/public;
    try_files $uri =404;
    access_log off;
    expires 30d;
    }
}